baseURL = "http://unwblog.s3-website-ap-southeast-2.amazonaws.com/"
languageCode = "en-au"
title = "Unwritten blog"
theme = "mediumish-gohugo-theme"
summaryLength = 25
publishDir = "docs"
alertbar = "false"

[params]
  logo = "/images/favicon.ico"
  description ="the clean blog!"

[params.index]
  title = "Luan's Top Blog "
  subtitle = "Welcome to Luan's blog "
  alertbar = false

## Main Menu
[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "blog"
    url = "/blog"